# Generated by Django 5.2.1 on 2025-07-12 13:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0002_uploadmodel'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UploadModel',
        ),
    ]
