# Generated by Django 5.2.1 on 2025-07-12 13:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0004_uploadmodel'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customerreview',
            name='hotel',
        ),
        migrations.RemoveField(
            model_name='kitchenimage',
            name='hotel',
        ),
        migrations.RemoveField(
            model_name='uploadmodel',
            name='hotel',
        ),
        migrations.DeleteModel(
            name='Certificate',
        ),
        migrations.DeleteModel(
            name='CustomerReview',
        ),
        migrations.DeleteModel(
            name='KitchenImage',
        ),
        migrations.DeleteModel(
            name='tbl_hotel',
        ),
        migrations.DeleteModel(
            name='UploadModel',
        ),
    ]
