# Generated by Django 5.2.1 on 2025-07-12 13:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('User', '0005_remove_customerreview_hotel_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='tbl_hotel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hotel_name', models.CharField(max_length=100)),
                ('hotel_email', models.EmailField(max_length=254, unique=True)),
                ('hotel_password', models.CharField(max_length=128)),
                ('hotel_contact', models.CharField(blank=True, max_length=20)),
                ('hotel_address', models.CharField(blank=True, max_length=255)),
                ('is_verified', models.IntegerField(choices=[(0, 'Not Verified'), (1, 'Verified'), (2, 'Rejected')], default=0)),
                ('hygiene_status', models.CharField(choices=[('Pending', 'Pending'), ('Clean', 'Clean'), ('Moderately Clean', 'Moderately Clean'), ('Dirty', 'Dirty')], default='Pending', max_length=50)),
                ('certificate_generated', models.BooleanField(default=False)),
                ('verified_at', models.DateTimeField(blank=True, null=True)),
            ],
        ),
    ]
