# Generated by Django 5.2.4 on 2025-07-12 17:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0007_certificate_customerreview_kitchenimage_uploadmodel'),
    ]

    operations = [
        migrations.CreateModel(
            name='HygieneViolation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('issue_date', models.DateField(auto_now_add=True)),
                ('hygiene_status', models.CharField(max_length=50)),
                ('pdf_file', models.FileField(blank=True, null=True, upload_to='violation_reports/')),
                ('hotel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='User.tbl_hotel')),
            ],
        ),
    ]
