# Generated by Django 5.2.7 on 2026-01-10 16:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("User", "0008_hygieneviolation"),
    ]

    operations = [
        migrations.AddField(
            model_name="uploadmodel",
            name="video",
            field=models.FileField(blank=True, null=True, upload_to="uploads/videos/"),
        ),
        migrations.AlterField(
            model_name="uploadmodel",
            name="image",
            field=models.ImageField(blank=True, null=True, upload_to="uploads/"),
        ),
    ]
