# Generated by Django 5.2.7 on 2026-01-17 06:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("User", "0009_uploadmodel_video_alter_uploadmodel_image"),
    ]

    operations = [
        migrations.AddField(
            model_name="certificate",
            name="certificate_number",
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name="certificate",
            name="file",
            field=models.FileField(blank=True, null=True, upload_to="certificates/"),
        ),
        migrations.AddField(
            model_name="uploadmodel",
            name="hygiene_status",
            field=models.CharField(default="Pending", max_length=50),
        ),
    ]
