# Generated by Django 5.2.7 on 2026-01-17 08:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("User", "0010_certificate_certificate_number_certificate_file_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="PublicComplaint",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "image",
                    models.ImageField(
                        blank=True, null=True, upload_to="public_complaints/images/"
                    ),
                ),
                (
                    "video",
                    models.FileField(
                        blank=True, null=True, upload_to="public_complaints/videos/"
                    ),
                ),
                ("description", models.TextField(blank=True)),
                ("ai_status", models.CharField(default="Pending", max_length=50)),
                ("priority", models.CharField(default="Low", max_length=20)),
                ("submitted_at", models.DateTimeField(auto_now_add=True)),
                (
                    "hotel",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="User.tbl_hotel"
                    ),
                ),
            ],
        ),
    ]
