# Generated by Django 5.2.11 on 2026-03-14 03:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0011_publiccomplaint'),
    ]

    operations = [
        migrations.CreateModel(
            name='HotelWarning',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField()),
                ('is_read', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('complaint', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='User.publiccomplaint')),
                ('hotel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='User.tbl_hotel')),
            ],
        ),
    ]
