# Generated by Django 5.2.11 on 2026-03-14 04:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0012_hotelwarning'),
    ]

    operations = [
        migrations.AddField(
            model_name='hotelwarning',
            name='violation',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='User.hygieneviolation'),
        ),
    ]
