# Generated by Django 5.2.11 on 2026-03-14 04:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0013_hotelwarning_violation'),
    ]

    operations = [
        migrations.AddField(
            model_name='hygieneviolation',
            name='complaint',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='User.publiccomplaint'),
        ),
    ]
