# Generated by Django 5.2.11 on 2026-03-14 04:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0014_hygieneviolation_complaint'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hygieneviolation',
            name='issue_date',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
