# Generated by Django 5.2.11 on 2026-03-15 03:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0015_alter_hygieneviolation_issue_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='hotelwarning',
            name='fine_amount',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AddField(
            model_name='hygieneviolation',
            name='fine_amount',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
    ]
