# Generated by Django 5.2.11 on 2026-03-15 05:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0016_hotelwarning_fine_amount_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customerreview',
            name='customer_name',
            field=models.CharField(default='Guest', max_length=100),
        ),
    ]
