# Generated by Django 5.2.11 on 2026-03-15 05:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0017_customerreview_customer_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customerreview',
            name='customer_name',
            field=models.CharField(blank=True, default='Anonymous Guest', max_length=100),
        ),
    ]
