"""
PDF Generation Utilities for RateMyKitchen
Generates violation reports and certificates
"""

from reportlab.lib.pagesizes import letter, A4
from reportlab.lib.units import inch
from reportlab.pdfgen import canvas
from reportlab.lib import colors
from reportlab.platypus import Table, TableStyle
from datetime import datetime, timedelta
import os


def generate_violation_report(hotel, upload_model, violations_list, output_path):
    """
    Generate PDF report for dirty or moderately clean kitchens
    
    Args:
        hotel: tbl_hotel instance
        upload_model: UploadModel instance with hygiene_status
        violations_list: List of detected violations
        output_path: Path to save the PDF
    
    Returns:
        Path to generated PDF
    """
    c = canvas.Canvas(output_path, pagesize=letter)
    width, height = letter
    
    # Header
    c.setFillColorRGB(0.79, 0.66, 0.38)  # Gold color
    c.rect(0, height - 100, width, 100, fill=True, stroke=False)
    
    c.setFillColorRGB(1, 1, 1)  # White text
    c.setFont("Helvetica-Bold", 24)
    c.drawCentredString(width / 2, height - 50, "HYGIENE VIOLATION REPORT")
    
    c.setFont("Helvetica", 12)
    c.drawCentredString(width / 2, height - 75, "RateMyKitchen AI Analysis")
    
    # Hotel Information
    y_position = height - 140
    c.setFillColorRGB(0, 0, 0)
    c.setFont("Helvetica-Bold", 14)
    c.drawString(50, y_position, "Hotel Information")
    
    y_position -= 25
    c.setFont("Helvetica", 11)
    c.drawString(70, y_position, f"Hotel Name: {hotel.hotel_name}")
    y_position -= 20
    c.drawString(70, y_position, f"Address: {hotel.hotel_address}")
    y_position -= 20
    c.drawString(70, y_position, f"Contact: {hotel.hotel_contact}")
    
    # Analysis Details
    y_position -= 40
    c.setFont("Helvetica-Bold", 14)
    c.drawString(50, y_position, "Analysis Details")
    
    y_position -= 25
    c.setFont("Helvetica", 11)
    c.drawString(70, y_position, f"Scan Date: {upload_model.uploaded_at.strftime('%B %d, %Y at %I:%M %p')}")
    y_position -= 20
    
    # Hygiene Status with color
    status = upload_model.hygiene_status
    if status == "Dirty":
        c.setFillColorRGB(0.93, 0.27, 0.27)  # Red
    else:  # Moderately Clean
        c.setFillColorRGB(0.96, 0.62, 0.04)  # Orange
    
    c.setFont("Helvetica-Bold", 12)
    c.drawString(70, y_position, f"Hygiene Status: {status}")
    
    # Violations Section
    y_position -= 40
    c.setFillColorRGB(0, 0, 0)
    c.setFont("Helvetica-Bold", 14)
    c.drawString(50, y_position, "Violations Detected")
    
    y_position -= 25
    c.setFont("Helvetica", 11)
    
    if violations_list:
        for i, violation in enumerate(violations_list, 1):
            if y_position < 100:  # New page if needed
                c.showPage()
                y_position = height - 50
            
            c.setFillColorRGB(0.93, 0.27, 0.27)
            c.circle(80, y_position + 3, 3, fill=True)
            c.setFillColorRGB(0, 0, 0)
            c.drawString(95, y_position, f"{violation.capitalize()}")
            y_position -= 20
    else:
        c.drawString(70, y_position, "No specific violations detected")
        y_position -= 20
    
    # Recommendations
    y_position -= 30
    if y_position < 200:
        c.showPage()
        y_position = height - 50
    
    c.setFont("Helvetica-Bold", 14)
    c.drawString(50, y_position, "Recommendations")
    
    y_position -= 25
    c.setFont("Helvetica", 10)
    recommendations = [
        "• Immediate deep cleaning of all kitchen surfaces required",
        "• Address all detected violations before resuming operations",
        "• Implement strict hygiene protocols and staff training",
        "• Schedule follow-up inspection within 7 days",
        "• Maintain daily cleaning logs and documentation"
    ]
    
    for rec in recommendations:
        if y_position < 100:
            c.showPage()
            y_position = height - 50
        c.drawString(70, y_position, rec)
        y_position -= 18
    
    # Footer
    c.setFillColorRGB(0.5, 0.5, 0.5)
    c.setFont("Helvetica-Oblique", 9)
    c.drawCentredString(width / 2, 50, "This report was generated by RateMyKitchen AI Analysis System")
    c.drawCentredString(width / 2, 35, f"Generated on: {datetime.now().strftime('%B %d, %Y at %I:%M %p')}")
    
    c.save()
    return output_path


def generate_certificate(hotel, upload_model, output_path):
    """
    Generate certificate PDF for clean kitchens
    
    Args:
        hotel: tbl_hotel instance
        upload_model: UploadModel instance
        output_path: Path to save the PDF
    
    Returns:
        Path to generated PDF
    """
    c = canvas.Canvas(output_path, pagesize=letter)
    width, height = letter
    
    # Decorative border
    c.setStrokeColorRGB(0.79, 0.66, 0.38)  # Gold
    c.setLineWidth(3)
    c.rect(30, 30, width - 60, height - 60, fill=False, stroke=True)
    
    c.setLineWidth(1)
    c.rect(40, 40, width - 80, height - 80, fill=False, stroke=True)
    
    # Header
    c.setFillColorRGB(0.79, 0.66, 0.38)
    c.setFont("Helvetica-Bold", 32)
    c.drawCentredString(width / 2, height - 120, "CERTIFICATE")
    
    c.setFont("Helvetica", 16)
    c.drawCentredString(width / 2, height - 150, "OF KITCHEN HYGIENE EXCELLENCE")
    
    # Decorative line
    c.setStrokeColorRGB(0.79, 0.66, 0.38)
    c.setLineWidth(2)
    c.line(150, height - 170, width - 150, height - 170)
    
    # Certificate body
    c.setFillColorRGB(0, 0, 0)
    c.setFont("Helvetica", 14)
    c.drawCentredString(width / 2, height - 220, "This is to certify that")
    
    # Hotel name
    c.setFont("Helvetica-Bold", 22)
    c.setFillColorRGB(0.79, 0.66, 0.38)
    c.drawCentredString(width / 2, height - 260, hotel.hotel_name.upper())
    
    # Certificate text
    c.setFillColorRGB(0, 0, 0)
    c.setFont("Helvetica", 13)
    c.drawCentredString(width / 2, height - 300, "has successfully passed the AI-powered kitchen hygiene inspection")
    c.drawCentredString(width / 2, height - 325, "and has been awarded this certificate for maintaining")
    
    c.setFont("Helvetica-Bold", 15)
    c.setFillColorRGB(0.13, 0.72, 0.51)  # Green
    c.drawCentredString(width / 2, height - 355, "EXCELLENT HYGIENE STANDARDS")
    
    # Details
    c.setFillColorRGB(0, 0, 0)
    c.setFont("Helvetica", 11)
    
    issue_date = datetime.now()
    valid_till = issue_date + timedelta(days=90)  # Valid for 90 days
    
    y_pos = height - 420
    c.drawString(120, y_pos, f"Certificate Number:")
    c.setFont("Helvetica-Bold", 11)
    cert_number = f"RMK-{hotel.id}-{issue_date.strftime('%Y%m%d')}"
    c.drawString(260, y_pos, cert_number)
    
    y_pos -= 25
    c.setFont("Helvetica", 11)
    c.drawString(120, y_pos, f"Issue Date:")
    c.setFont("Helvetica-Bold", 11)
    c.drawString(260, y_pos, issue_date.strftime('%B %d, %Y'))
    
    y_pos -= 25
    c.setFont("Helvetica", 11)
    c.drawString(120, y_pos, f"Valid Until:")
    c.setFont("Helvetica-Bold", 11)
    c.drawString(260, y_pos, valid_till.strftime('%B %d, %Y'))
    
    y_pos -= 25
    c.setFont("Helvetica", 11)
    c.drawString(120, y_pos, f"Hotel Address:")
    c.setFont("Helvetica-Bold", 11)
    c.drawString(260, y_pos, hotel.hotel_address[:40])
    
    # Signature section
    y_pos = 180
    c.setFont("Helvetica", 10)
    c.setFillColorRGB(0, 0, 0)
    
    # Left signature
    c.line(100, y_pos, 250, y_pos)
    c.drawCentredString(175, y_pos - 20, "Authorized Signature")
    c.setFont("Helvetica-Oblique", 9)
    c.drawCentredString(175, y_pos - 35, "RateMyKitchen AI System")
    
    # Right signature
    c.setFont("Helvetica", 10)
    c.line(width - 250, y_pos, width - 100, y_pos)
    c.drawCentredString(width - 175, y_pos - 20, "Date of Issue")
    c.setFont("Helvetica-Bold", 9)
    c.drawCentredString(width - 175, y_pos - 35, issue_date.strftime('%B %d, %Y'))
    
    # Seal/Badge
    c.setFillColorRGB(0.79, 0.66, 0.38)
    c.setStrokeColorRGB(0.79, 0.66, 0.38)
    c.setLineWidth(2)
    c.circle(width - 100, height - 120, 40, fill=False, stroke=True)
    c.setFont("Helvetica-Bold", 10)
    c.drawCentredString(width - 100, height - 115, "CERTIFIED")
    c.setFont("Helvetica", 8)
    c.drawCentredString(width - 100, height - 130, "CLEAN")
    
    # Footer
    c.setFillColorRGB(0.5, 0.5, 0.5)
    c.setFont("Helvetica-Oblique", 8)
    c.drawCentredString(width / 2, 60, "This certificate is valid for 90 days from the date of issue")
    c.drawCentredString(width / 2, 45, "RateMyKitchen - AI-Powered Kitchen Hygiene Intelligence")
    
    c.save()
    return output_path
